package com.karimandco.pdf;

import com.itextpdf.text.BadElementException;
import java.awt.Color;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author Tom, Léo, Lorenzo
 */
public class PanelPDF extends javax.swing.JPanel {

    /**
     * Crée le composant PanelPDF.
     * 
     */
    public PanelPDF() {
        initComponents();
        lienPDF= "";
        jLabelLienPDF.setForeground(Color.red);
        jLabelLienPDF.setText("Choisissez un dossier");
        
        nom="FREGOLENT";
        prenom="Damien";
        numero="06 37 80 45 65";
    }

    public void setNom(String nom) {
        this.nom = nom;
    }

    public void setPrenom(String prenom) {
        this.prenom = prenom;
    }

    public void setNumero(String numero) {
        this.numero = numero;
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelLienPDF = new javax.swing.JLabel();
        jButtonChoisirBouton = new javax.swing.JButton();
        jButtonEnregistrerPDF = new javax.swing.JButton();

        jLabelLienPDF.setText("jLabel1");

        jButtonChoisirBouton.setText("Choisir un dossier");
        jButtonChoisirBouton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonChoisirBoutonMouseClicked(evt);
            }
        });
        jButtonChoisirBouton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonChoisirBoutonActionPerformed(evt);
            }
        });

        jButtonEnregistrerPDF.setText("Enregistrer");
        jButtonEnregistrerPDF.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonEnregistrerPDFMouseClicked(evt);
            }
        });
        jButtonEnregistrerPDF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEnregistrerPDFActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelLienPDF, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButtonChoisirBouton)
                .addGap(18, 18, 18)
                .addComponent(jButtonEnregistrerPDF)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelLienPDF)
                    .addComponent(jButtonChoisirBouton)
                    .addComponent(jButtonEnregistrerPDF))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonChoisirBoutonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonChoisirBoutonMouseClicked
        int result;
        File dossierChoisi;
        String lienDossier;
        
        result = selectPDF.getChoisirDossier().showOpenDialog(this);
        
        if (result == JFileChooser.APPROVE_OPTION) {
            dossierChoisi=selectPDF.getChoisirDossier().getSelectedFile();
            lienDossier = dossierChoisi.toString();
            this.lienPDF=lienDossier;
            jLabelLienPDF.setForeground(Color.black);
            jLabelLienPDF.setText(lienPDF);
        } else if(result == JFileChooser.CANCEL_OPTION) {
//            System.out.println("PAS OK");
        }
    }//GEN-LAST:event_jButtonChoisirBoutonMouseClicked

    private void jButtonEnregistrerPDFMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonEnregistrerPDFMouseClicked
        Pdf pdf = new Pdf(nom, prenom, numero, lienPDF);
        System.out.println(lienPDF);
        if (pdf.verifPDF()) {
            try {
                pdf.genererPDF();
                JOptionPane.showMessageDialog(this, "cv.pdf a été enregistré dans "+lienPDF);
            } catch (FileNotFoundException ex) {
                JOptionPane.showConfirmDialog(this, "Erreur");
            } catch (BadElementException ex) {
                Logger.getLogger(PanelPDF.class.getName()).log(Level.SEVERE, null, ex);
            } catch (IOException ex) {
                Logger.getLogger(PanelPDF.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else {
            JOptionPane.showConfirmDialog(this, "Pas ok, c'est pas bon");
        }
    }//GEN-LAST:event_jButtonEnregistrerPDFMouseClicked

    private void jButtonEnregistrerPDFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEnregistrerPDFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonEnregistrerPDFActionPerformed

    private void jButtonChoisirBoutonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonChoisirBoutonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonChoisirBoutonActionPerformed


    public String lienPDF;
    public SelectionnerPDF selectPDF = new SelectionnerPDF();
    private String nom="";
    private String prenom="";
    private String numero="";
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonChoisirBouton;
    private javax.swing.JButton jButtonEnregistrerPDF;
    private javax.swing.JLabel jLabelLienPDF;
    // End of variables declaration//GEN-END:variables
}
