/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.karimandco.admin;

import java.awt.Color;
import java.awt.event.KeyEvent;
import java.awt.event.KeyListener;
import com.karimandco.auth.*;
import com.karimandco.bdd.DaoSIO;

/**
 *
 * @author t.normand
 */
public class PanneauFormModification extends javax.swing.JPanel {

    Modification panneauPereModification = null;
    private Boolean nomOK = false;
    private Boolean prenomOK = false;
    private Boolean identifiantOK = false;
    private Boolean courrielOK = false;
    private Boolean numeroTelephoneOK = false;
    private Boolean dateNaissanceOK = false;
    private Integer ligne_selectionnee;


    /**
     * Creates new form PanneauFormModification
     */
    public PanneauFormModification() {
        initComponents();

        panneauNom.setjLabelNomChamp("Nom");
        panneauPrenom.setjLabelNomChamp("Prénom");
        panneauIdentifiant.setjLabelNomChamp("Identifiant");
        panneauCourriel.setjLabelNomChamp("Courriel");
        panneauNumeroTelephone.setjLabelNomChamp("Numéro de téléphone");
        panneauDateNaissance.setjLabelNomChamp("Date de naissance (jj/mm/aaaa)");

        KeyListener(panneauNom, 0);
        KeyListener(panneauPrenom, 1);
        KeyListener(panneauIdentifiant, 2);
        KeyListener(panneauCourriel, 3);
        KeyListener(panneauNumeroTelephone, 4);
        KeyListener(panneauDateNaissance, 5);
    }

    public void setFenParentModification(Modification i) {
        this.panneauPereModification = i;
    }

    public void setNomOK(Boolean nomOK) {
        this.nomOK = nomOK;
    }

    public void setPrenomOK(Boolean prenomOK) {
        this.prenomOK = prenomOK;
    }

    public void setIdentifiantOK(Boolean identifiantOK) {
        this.identifiantOK = identifiantOK;
    }

    public void setCourrielOK(Boolean courrielOK) {
        this.courrielOK = courrielOK;
    }

    public void setNumeroTelephoneOK(Boolean numeroTelephoneOK) {
        this.numeroTelephoneOK = numeroTelephoneOK;
    }

    public void setDateNaissanceOK(Boolean dateNaissanceOK) {
        this.dateNaissanceOK = dateNaissanceOK;
    }

    public PanneauChamp getPanneauCourriel() {
        return panneauCourriel;
    }

    public void setPanneauCourriel(PanneauChamp panneauCourriel) {
        this.panneauCourriel = panneauCourriel;
    }

    public PanneauChamp getPanneauDateNaissance() {
        return panneauDateNaissance;
    }

    public void setPanneauDateNaissance(PanneauChamp panneauDateNaissance) {
        this.panneauDateNaissance = panneauDateNaissance;
    }

    public PanneauChamp getPanneauIdentifiant() {
        return panneauIdentifiant;
    }

    public void setPanneauIdentifiant(PanneauChamp panneauIdentifiant) {
        this.panneauIdentifiant = panneauIdentifiant;
    }

    public PanneauChamp getPanneauNom() {
        return panneauNom;
    }

    public Integer getLigne_selectionnee() {
        return ligne_selectionnee;
    }

    public void setLigne_selectionnee(Integer ligne_selectionnee) {
        this.ligne_selectionnee = ligne_selectionnee;
    }

    public void setPanneauNom(PanneauChamp panneauNom) {
        this.panneauNom = panneauNom;
    }

    public PanneauChamp getPanneauNumeroTelephone() {
        return panneauNumeroTelephone;
    }

    public void setPanneauNumeroTelephone(PanneauChamp panneauNumeroTelephone) {
        this.panneauNumeroTelephone = panneauNumeroTelephone;
    }

    public PanneauChamp getPanneauPrenom() {
        return panneauPrenom;
    }

    public void setPanneauPrenom(PanneauChamp panneauPrenom) {
        this.panneauPrenom = panneauPrenom;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panneauNom = new com.karimandco.auth.PanneauChamp();
        panneauPrenom = new com.karimandco.auth.PanneauChamp();
        panneauIdentifiant = new com.karimandco.auth.PanneauChamp();
        panneauCourriel = new com.karimandco.auth.PanneauChamp();
        panneauNumeroTelephone = new com.karimandco.auth.PanneauChamp();
        panneauDateNaissance = new com.karimandco.auth.PanneauChamp();
        jButton1 = new javax.swing.JButton();
        jLabelEtatInscription = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        jButton1.setText("Appliquer les changements");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabelEtatInscription.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Modification d'utilisateur");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(panneauNom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(panneauPrenom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(panneauIdentifiant, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(panneauCourriel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(panneauNumeroTelephone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(panneauDateNaissance, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelEtatInscription, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(panneauPrenom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panneauNom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panneauIdentifiant, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panneauCourriel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panneauNumeroTelephone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panneauDateNaissance, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelEtatInscription, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if (nomOK && prenomOK && identifiantOK && courrielOK && numeroTelephoneOK && dateNaissanceOK) {
            String[] date_split = this.panneauDateNaissance.getChamp2().getText().split("/");
            String date_newFormat = date_split[2] + "-" + date_split[1] + "-" + date_split[0];            
            Integer resultat = DaoSIO.getInstance().requeteAction("UPDATE utilisateurs SET nom = '" + this.panneauNom.getChamp2().getText() + "', prenom = '" +  this.panneauPrenom.getChamp2().getText() + "', identifiant = '" + this.panneauIdentifiant.getChamp2().getText() + "', courriel = '" + this.panneauCourriel.getChamp2().getText() + "', num_telephone = '" + this.panneauNumeroTelephone.getChamp2().getText() + "', date_de_naissance = '" + date_newFormat + "' WHERE id = '" + this.getLigne_selectionnee() + "'");
            if (resultat > 0) {
                panneauPereModification.getObjAutreFenetreAdmin().getjLabelEtatVider().setForeground(Color.blue);
                panneauPereModification.getObjAutreFenetreAdmin().getjLabelEtatVider().setText("Modification réussie");
                panneauPereModification.getObjAutreFenetreAdmin().updateJTableInfo();
                panneauPereModification.getObjAutreFenetreAdmin().cModification.setVisible(false);
                
            } else {
                panneauPereModification.setForeground(Color.red);
                panneauPereModification.getObjAutreFenetreAdmin().getjLabelEtatVider().setText("Echec de la modification");
            }
        } else {
            panneauPereModification.setForeground(Color.black);
            panneauPereModification.getObjAutreFenetreAdmin().getjLabelEtatVider().setText("");
        }
    }//GEN-LAST:event_jButton1ActionPerformed
    /**
     * Cette méthode permet de générer un KeyListener pour les panneaux champ.
     *
     * @param champ PanneauChamp champ
     * @param numeroVerif Integer numéro vérification
     */

    private void KeyListener(PanneauChamp champ, Integer numeroVerif) {
        champ.getChamp2().addKeyListener(new KeyListener() {
            @Override
            public void keyTyped(KeyEvent e) {
                // throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
            }

            @Override
            public void keyPressed(KeyEvent e) {
                // throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
            }

            @Override
            public void keyReleased(KeyEvent e) {
                // throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
                Boolean resultat = null;
                if (!champ.getChamp2().getText().equals("")) {
                    if (numeroVerif == 0) {
                        resultat = champ.getChamp2().verifNom();
                        setNomOK(resultat);
                    } else if (numeroVerif == 1) {
                        resultat = champ.getChamp2().verifPrenom();
                        setPrenomOK(resultat);
                    } else if (numeroVerif == 2) {
                        resultat = champ.getChamp2().verifIdentifiant();
                        setIdentifiantOK(resultat);
                    } else if (numeroVerif == 3) {
                        resultat = champ.getChamp2().verifCourriel();
                        setCourrielOK(resultat);
                    } else if (numeroVerif == 4) {
                        resultat = champ.getChamp2().verifNumeroTelephone();
                        setNumeroTelephoneOK(resultat);
                    } else if (numeroVerif == 5) {
                        resultat = champ.getChamp2().verifDateNaissance();
                        setDateNaissanceOK(resultat);
                    }

                    if (resultat == true) {
                        champ.setjLabelEtatChamp(Color.blue);
                        champ.setjLabelEtatChamp("Format correct");
                    } else {
                        champ.setjLabelEtatChamp(Color.red);
                        champ.setjLabelEtatChamp("Format incorrect");
                    }
                } else {
                    champ.setjLabelEtatChamp(Color.black);
                    champ.setjLabelEtatChamp("");
                }
            }
        });
    }

    public void updateJLabelEtat() {
        if (panneauNom.getChamp2().verifNom()) {
            panneauNom.setjLabelEtatChamp(Color.blue);
            panneauNom.setjLabelEtatChamp("Format correct");
            setNomOK(panneauNom.getChamp2().verifNom());
        } else {
            panneauNom.setjLabelEtatChamp(Color.red);
            panneauNom.setjLabelEtatChamp("Format incorrect");
        }

        if (panneauPrenom.getChamp2().verifPrenom()) {
            panneauPrenom.setjLabelEtatChamp(Color.blue);
            panneauPrenom.setjLabelEtatChamp("Format correct");
            setPrenomOK(panneauPrenom.getChamp2().verifPrenom());
        } else {
            panneauPrenom.setjLabelEtatChamp(Color.red);
            panneauPrenom.setjLabelEtatChamp("Format incorrect");
        }

        if (panneauIdentifiant.getChamp2().verifIdentifiant()) {
            panneauIdentifiant.setjLabelEtatChamp(Color.blue);
            panneauIdentifiant.setjLabelEtatChamp("Format correct");
            setIdentifiantOK(panneauIdentifiant.getChamp2().verifIdentifiant());
        } else {
            panneauIdentifiant.setjLabelEtatChamp(Color.red);
            panneauIdentifiant.setjLabelEtatChamp("Format incorrect");
        }

        if (panneauCourriel.getChamp2().verifCourriel()) {
            panneauCourriel.setjLabelEtatChamp(Color.blue);
            panneauCourriel.setjLabelEtatChamp("Format correct");
            setCourrielOK(panneauCourriel.getChamp2().verifCourriel());
        } else {
            panneauCourriel.setjLabelEtatChamp(Color.red);
            panneauCourriel.setjLabelEtatChamp("Format incorrect");
        }

        if (panneauNumeroTelephone.getChamp2().verifNumeroTelephone()) {
            panneauNumeroTelephone.setjLabelEtatChamp(Color.blue);
            panneauNumeroTelephone.setjLabelEtatChamp("Format correct");
            setNumeroTelephoneOK(panneauNumeroTelephone.getChamp2().verifNumeroTelephone());
        } else {
            panneauNumeroTelephone.setjLabelEtatChamp(Color.red);
            panneauNumeroTelephone.setjLabelEtatChamp("Format incorrect");
        }

        if (panneauDateNaissance.getChamp2().verifDateNaissance()) {
            panneauDateNaissance.setjLabelEtatChamp(Color.blue);
            panneauDateNaissance.setjLabelEtatChamp("Format correct");
            setDateNaissanceOK(panneauDateNaissance.getChamp2().verifDateNaissance());
        } else {
            panneauDateNaissance.setjLabelEtatChamp(Color.red);
            panneauDateNaissance.setjLabelEtatChamp("Format incorrect");
        }
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelEtatInscription;
    private com.karimandco.auth.PanneauChamp panneauCourriel;
    private com.karimandco.auth.PanneauChamp panneauDateNaissance;
    private com.karimandco.auth.PanneauChamp panneauIdentifiant;
    private com.karimandco.auth.PanneauChamp panneauNom;
    private com.karimandco.auth.PanneauChamp panneauNumeroTelephone;
    private com.karimandco.auth.PanneauChamp panneauPrenom;
    // End of variables declaration//GEN-END:variables
}
