/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.karimandco.end;

import com.karimandco.auth.Utilisateur;
import com.karimandco.importexport.ImportExportCSV;
import com.karimandco.importexport.ImportExportJSON;
import com.karimandco.importexport.ImportExportXML;
import java.awt.Color;
import javax.swing.JMenu;
import javax.swing.JOptionPane;
/**
 *
 * @author f.bruckmann
 */
public class KarimAndCoInterface extends javax.swing.JFrame {
    /**
     * Creates new form JFrameKarimAndCo
     */
    public KarimAndCoInterface() {
        initComponents();
        getContentPane().setBackground(new Color(0,102,153));
        creationDuCV1.setIdUtilisateur(Utilisateur.getInstance().getId());
        init();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jCheckBoxMenuItem1 = new javax.swing.JCheckBoxMenuItem();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu8 = new javax.swing.JMenu();
        jMenu9 = new javax.swing.JMenu();
        jMenuBar3 = new javax.swing.JMenuBar();
        jMenu10 = new javax.swing.JMenu();
        jMenu11 = new javax.swing.JMenu();
        menuBar1 = new java.awt.MenuBar();
        menu1 = new java.awt.Menu();
        menu2 = new java.awt.Menu();
        popupMenu1 = new java.awt.PopupMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jLayeredPane3 = new javax.swing.JLayeredPane();
        jPopupMenu1 = new javax.swing.JPopupMenu();
        jPanel1 = new javax.swing.JPanel();
        creationDuCV1 = new com.karimandco.cv.CreationDuCV();
        jLayeredPane4 = new javax.swing.JLayeredPane();
        choisirImage1 = new com.karimandco.image.ChoisirImage();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        voirPdf1 = new com.karimandco.pdf.VoirPdf();
        jLayeredPane2 = new javax.swing.JLayeredPane();
        panneauAdministration1 = new com.karimandco.admin.PanneauAdministration();
        jMenuBarKAC = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuCreationCV = new javax.swing.JMenu();
        jMenuImage = new javax.swing.JMenu();
        jMenuImportationCVPDF = new javax.swing.JMenu();
        jMenuAdmin = new javax.swing.JMenu();
        XML = new javax.swing.JMenuItem();
        JSON = new javax.swing.JMenuItem();
        CSV = new javax.swing.JMenuItem();
        administration = new javax.swing.JMenuItem();
        jMenuDeconnexion = new javax.swing.JMenu();

        jCheckBoxMenuItem1.setSelected(true);
        jCheckBoxMenuItem1.setText("jCheckBoxMenuItem1");

        jMenu8.setText("File");
        jMenuBar2.add(jMenu8);

        jMenu9.setText("Edit");
        jMenuBar2.add(jMenu9);

        jMenu10.setText("File");
        jMenuBar3.add(jMenu10);

        jMenu11.setText("Edit");
        jMenuBar3.add(jMenu11);

        menu1.setLabel("File");
        menuBar1.add(menu1);

        menu2.setLabel("Edit");
        menuBar1.add(menu2);

        popupMenu1.setLabel("popupMenu1");

        jMenuItem1.setText("jMenuItem1");

        javax.swing.GroupLayout jLayeredPane3Layout = new javax.swing.GroupLayout(jLayeredPane3);
        jLayeredPane3.setLayout(jLayeredPane3Layout);
        jLayeredPane3Layout.setHorizontalGroup(
            jLayeredPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jLayeredPane3Layout.setVerticalGroup(
            jLayeredPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 102, 153));

        jPanel1.setBackground(new java.awt.Color(0, 102, 153));

        creationDuCV1.setPreferredSize(new java.awt.Dimension(1612, 648));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(249, Short.MAX_VALUE)
                .addComponent(creationDuCV1, javax.swing.GroupLayout.PREFERRED_SIZE, 1117, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(246, 246, 246))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(creationDuCV1, javax.swing.GroupLayout.DEFAULT_SIZE, 765, Short.MAX_VALUE)
        );

        jLayeredPane4.setBackground(new java.awt.Color(0, 102, 153));
        jLayeredPane4.setPreferredSize(new java.awt.Dimension(1612, 648));

        choisirImage1.setBackground(new java.awt.Color(0, 102, 153));
        choisirImage1.setPreferredSize(new java.awt.Dimension(1612, 648));

        jLayeredPane4.setLayer(choisirImage1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane4Layout = new javax.swing.GroupLayout(jLayeredPane4);
        jLayeredPane4.setLayout(jLayeredPane4Layout);
        jLayeredPane4Layout.setHorizontalGroup(
            jLayeredPane4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane4Layout.createSequentialGroup()
                .addGap(495, 495, 495)
                .addComponent(choisirImage1, javax.swing.GroupLayout.PREFERRED_SIZE, 611, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(506, Short.MAX_VALUE))
        );
        jLayeredPane4Layout.setVerticalGroup(
            jLayeredPane4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane4Layout.createSequentialGroup()
                .addGap(109, 109, 109)
                .addComponent(choisirImage1, javax.swing.GroupLayout.PREFERRED_SIZE, 412, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(258, Short.MAX_VALUE))
        );

        jLayeredPane1.setBackground(new java.awt.Color(0, 102, 153));
        jLayeredPane1.setPreferredSize(new java.awt.Dimension(1612, 648));

        jLayeredPane1.setLayer(voirPdf1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(voirPdf1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(995, Short.MAX_VALUE))
        );
        jLayeredPane1Layout.setVerticalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                .addComponent(voirPdf1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 548, Short.MAX_VALUE))
        );

        jLayeredPane2.setBackground(new java.awt.Color(0, 102, 153));

        panneauAdministration1.setBackground(new java.awt.Color(0, 102, 153));

        jLayeredPane2.setLayer(panneauAdministration1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane2Layout = new javax.swing.GroupLayout(jLayeredPane2);
        jLayeredPane2.setLayout(jLayeredPane2Layout);
        jLayeredPane2Layout.setHorizontalGroup(
            jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane2Layout.createSequentialGroup()
                .addComponent(panneauAdministration1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jLayeredPane2Layout.setVerticalGroup(
            jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panneauAdministration1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        jMenuBarKAC.setBackground(new java.awt.Color(0, 0, 0));
        jMenuBarKAC.setForeground(new java.awt.Color(255, 255, 255));

        jMenu1.setForeground(new java.awt.Color(204, 51, 0));
        jMenu1.setText("KARIMANDCO SOFTWARE");
        jMenuBarKAC.add(jMenu1);

        jMenuCreationCV.setText("Création du CV");
        jMenuCreationCV.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuCreationCVMouseClicked(evt);
            }
        });
        jMenuBarKAC.add(jMenuCreationCV);

        jMenuImage.setText("Changer photo personnelle");
        jMenuImage.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuImageMouseClicked(evt);
            }
        });
        jMenuBarKAC.add(jMenuImage);

        jMenuImportationCVPDF.setText("Obtenir CV");
        jMenuImportationCVPDF.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuImportationCVPDFMouseClicked(evt);
            }
        });
        jMenuBarKAC.add(jMenuImportationCVPDF);

        jMenuAdmin.setText("Espace Administration");

        XML.setText("Donnée XML");
        XML.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                XMLActionPerformed(evt);
            }
        });
        jMenuAdmin.add(XML);

        JSON.setText("Donnée JSON");
        JSON.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JSONActionPerformed(evt);
            }
        });
        jMenuAdmin.add(JSON);

        CSV.setText("Donnée CSV");
        CSV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CSVActionPerformed(evt);
            }
        });
        jMenuAdmin.add(CSV);

        administration.setText("Interface administratif");
        administration.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                administrationActionPerformed(evt);
            }
        });
        jMenuAdmin.add(administration);

        jMenuBarKAC.add(jMenuAdmin);

        jMenuDeconnexion.setText("Déconnexion");
        jMenuDeconnexion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuDeconnexionMouseClicked(evt);
            }
        });
        jMenuBarKAC.add(jMenuDeconnexion);

        setJMenuBar(jMenuBarKAC);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(24, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 24, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jLayeredPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jLayeredPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(18, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jLayeredPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 761, Short.MAX_VALUE)
                    .addGap(12, 12, 12)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jLayeredPane2)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jLayeredPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 779, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void init() {
        creationDuCV1.show();
        voirPdf1.hide();
        panneauAdministration1.hide();
        choisirImage1.hide();
        jMenuAdmin.setVisible(false);
    }

    public KarimAndCoSoftware jFramePere;
    public KarimAndCoInterface jFrameLogAdmin;
    public Integer statut = null;


    private void jMenuCreationCVMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuCreationCVMouseClicked
        creationDuCV1.show();
        voirPdf1.hide();
        panneauAdministration1.hide();
        choisirImage1.hide();
    }//GEN-LAST:event_jMenuCreationCVMouseClicked

    private void jMenuDeconnexionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuDeconnexionMouseClicked
        this.jFramePere = new KarimAndCoSoftware();
        Utilisateur.getInstance().setEstConnecte(false);
        System.out.println(Utilisateur.getInstance().getEstConnecte());
        jFramePere.setVisible(true); // c'est ici qu'on pourra faire des zones grisées.
        this.setVisible(false);
    }//GEN-LAST:event_jMenuDeconnexionMouseClicked

    private void jMenuImportationCVPDFMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuImportationCVPDFMouseClicked
        voirPdf1.show();
        creationDuCV1.hide();
        panneauAdministration1.hide();
        choisirImage1.hide();
    }//GEN-LAST:event_jMenuImportationCVPDFMouseClicked

    private void jMenuImageMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuImageMouseClicked
        choisirImage1.show();
        voirPdf1.hide();
        creationDuCV1.hide();
        panneauAdministration1.hide();
    }//GEN-LAST:event_jMenuImageMouseClicked

    private void JSONActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JSONActionPerformed
        ImportExportJSON objJSON = new ImportExportJSON("src\\main\\java\\com\\karimandco\\importexport\\BddExporterJson.json");
        objJSON.exportFichier();
        JOptionPane.showMessageDialog(this, "L'importation des données en format JSON à été effectuée avec succès !", "IMPORTATION DES DONNEES", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_JSONActionPerformed

    private void XMLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_XMLActionPerformed
        ImportExportXML objEXML = new ImportExportXML("src\\main\\java\\com\\karimandco\\importexport\\BddExporterXml.xml");
        objEXML.exportFichier();
        JOptionPane.showMessageDialog(this, "L'importation des données en format XML à été effectuée avec succès !", "IMPORTATION DES DONNEES", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_XMLActionPerformed

    private void CSVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CSVActionPerformed
        ImportExportCSV objCSV = new ImportExportCSV("src\\main\\java\\com\\karimandco\\importexport\\BddExporterCsv.csv");
        objCSV.exportFichier();
        JOptionPane.showMessageDialog(this, "L'importation des données en format CSV à été effectuée avec succès !", "IMPORTATION DES DONNEES", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_CSVActionPerformed

    private void administrationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_administrationActionPerformed
        creationDuCV1.hide();
        voirPdf1.hide();
        panneauAdministration1.show();
        choisirImage1.hide();
    }//GEN-LAST:event_administrationActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(KarimAndCoInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(KarimAndCoInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(KarimAndCoInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(KarimAndCoInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new KarimAndCoInterface().setVisible(true);
            }
        });
    }

    public JMenu getjMenuInterfaceAdmin() {
        return jMenuAdmin;
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem CSV;
    private javax.swing.JMenuItem JSON;
    private javax.swing.JMenuItem XML;
    private javax.swing.JMenuItem administration;
    private com.karimandco.image.ChoisirImage choisirImage1;
    private com.karimandco.cv.CreationDuCV creationDuCV1;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem1;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JLayeredPane jLayeredPane2;
    private javax.swing.JLayeredPane jLayeredPane3;
    private javax.swing.JLayeredPane jLayeredPane4;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu10;
    private javax.swing.JMenu jMenu11;
    private javax.swing.JMenu jMenu8;
    private javax.swing.JMenu jMenu9;
    private javax.swing.JMenu jMenuAdmin;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuBar jMenuBar3;
    private javax.swing.JMenuBar jMenuBarKAC;
    private javax.swing.JMenu jMenuCreationCV;
    private javax.swing.JMenu jMenuDeconnexion;
    private javax.swing.JMenu jMenuImage;
    private javax.swing.JMenu jMenuImportationCVPDF;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPopupMenu jPopupMenu1;
    private java.awt.Menu menu1;
    private java.awt.Menu menu2;
    private java.awt.MenuBar menuBar1;
    private com.karimandco.admin.PanneauAdministration panneauAdministration1;
    private java.awt.PopupMenu popupMenu1;
    private com.karimandco.pdf.VoirPdf voirPdf1;
    // End of variables declaration//GEN-END:variables
}
